# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100)),
                ('page_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshots_date', models.CharField(max_length=100)),
                ('selected_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.Page')),
            ],
        ),
        migrations.CreateModel(
            name='PagePath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_path', models.CharField(max_length=100)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.PageData')),
            ],
        ),
    ]
