# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagepath',
            name='page_path',
            field=models.FilePathField(path='/fs/<django.db.models.query_utils.DeferredAttribute object at 0x000002BAB6658588><django.db.models.query_utils.DeferredAttribute object at 0x000002BAB66589B0>'),
        ),
    ]
