# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_auto_20170423_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagepath',
            name='page_path',
            field=models.FilePathField(path='/fs/<django.db.models.query_utils.DeferredAttribute object at 0x000001F678D3D438><django.db.models.query_utils.DeferredAttribute object at 0x000001F678D3D6D8>'),
        ),
    ]
