# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_auto_20170423_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagepath',
            name='page_path',
            field=models.FilePathField(path='/fs/<django.db.models.query_utils.DeferredAttribute object at 0x000002772F68D470><django.db.models.query_utils.DeferredAttribute object at 0x000002772F68D6D8>'),
        ),
    ]
