# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-03 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0009_auto_20170503_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagedata',
            name='snapshots_date',
            field=models.CharField(max_length=100),
        ),
    ]
