# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 08:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0011_auto_20170515_0754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='pagedata',
            options={'managed': True},
        ),
    ]
