# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-15 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0012_auto_20170515_0800'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='page',
            table='Page',
        ),
        migrations.AlterModelTable(
            name='pagedata',
            table='PageData',
        ),
    ]
