# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-15 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0013_auto_20170515_1206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pagedata',
            options={'managed': False},
        ),
    ]
