# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0014_auto_20170515_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(max_length=100)),
                ('extension_list', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'Restriction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Url_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'List',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'managed': False, 'ordering': ['page_name']},
        ),
    ]
