# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0015_auto_20170528_1041'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rejectlist',
            table='RejectList',
        ),
        migrations.AlterModelTable(
            name='url_list',
            table='Url_list',
        ),
    ]
