# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0016_auto_20170528_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_limit', models.IntegerField()),
                ('line_limit', models.IntegerField()),
                ('path', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name': 'Checking configuration',
                'db_table': 'Config',
                'managed': False,
            },
        ),
    ]
